// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8LpowdU0sgBAL9KhmuTM1jwUd8qh8YJ0',
    appId: '1:806095337181:web:c52b7d92e37996e80ecd34',
    messagingSenderId: '806095337181',
    projectId: 'agentportalcommisions',
    authDomain: 'agentportalcommisions.firebaseapp.com',
    storageBucket: 'agentportalcommisions.firebasestorage.app',
    measurementId: 'G-KQRF1TW5YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-QAwTbfR9dchXZm79XSVhYzzyyLpLDU',
    appId: '1:806095337181:android:07329bfd51e47e2d0ecd34',
    messagingSenderId: '806095337181',
    projectId: 'agentportalcommisions',
    storageBucket: 'agentportalcommisions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkwEWkpxyR5aXb9s1odi3Mf2mDGmOufA',
    appId: '1:806095337181:ios:5a11d62ba9c34f230ecd34',
    messagingSenderId: '806095337181',
    projectId: 'agentportalcommisions',
    storageBucket: 'agentportalcommisions.firebasestorage.app',
    iosBundleId: 'com.example.pdfManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkwEWkpxyR5aXb9s1odi3Mf2mDGmOufA',
    appId: '1:806095337181:ios:5a11d62ba9c34f230ecd34',
    messagingSenderId: '806095337181',
    projectId: 'agentportalcommisions',
    storageBucket: 'agentportalcommisions.firebasestorage.app',
    iosBundleId: 'com.example.pdfManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8LpowdU0sgBAL9KhmuTM1jwUd8qh8YJ0',
    appId: '1:806095337181:web:e2ed06dc28ba583d0ecd34',
    messagingSenderId: '806095337181',
    projectId: 'agentportalcommisions',
    authDomain: 'agentportalcommisions.firebaseapp.com',
    storageBucket: 'agentportalcommisions.firebasestorage.app',
    measurementId: 'G-374GFDDRF2',
  );
}
